baseURL = "https://spellborn.org/"
languageCode = "en-us"
title = "The Chronicles of Spellborn Reborn"
theme = "istani"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 20

  [[menu.main]]
    identifier = "forum"
    name = "Forum"
    url = "https://forum.spellborn.org"
    weight = 30


  [[menu.main]]
  	identifier = "game1"
	  parent = "The Game"
	  name = "High Houses"
	  url = "/content/high-houses/"
	  weight = 40
  
  [[menu.main]]
  	identifier = "game2"
	  parent = "The Game"
	  name = "Classes"
	  url = "/content/classes/"
	  weight = 41


  [[menu.main]]
    identifier = "client1"
    parent = "Installation"
    name = "Get Started"
    url = "/content/getting-started/"
    weight = 50

  [[menu.main]]
    identifier = "client2"
    parent = "Installation"
    name = "Download installer"
    url = "https://files.spellborn.org/launcher/installer.exe"
    weight = 51

  [[menu.main]]
    identifier = "Donate"
    name = "Donate"
    url = "https://donorbox.org/spellborn-reborn"
    weight = 40

  [[menu.footergame]]
    identifier = "highhouses"
    name = "High Houses"
    url = "/content/high-houses"
    weight = 10


  [[menu.footerquick]]
    identifier = "started"
    name = "Get Started"
    url = "/content/getting-started"
    weight = 10

  [[menu.footerquick]]
    identifier = "client"
    name = "Download installer/patcher"
    url = "https://files.spellborn.org/launcher/installer.exe"
    weight = 10


  [[menu.footermore]]
    identifier = "forum"
    name = "Forum"
    url = "https://forum.spellborn.org"
    weight = 10

  [[menu.footermore]]
    identifier = "discord"
    name = "Discord"
    url = "https://discord.gg/M8u7AsG"
    weight = 20
