baseURL = "https://spellborn.org/"
languageCode = "en-us"
title = "The Chronicles of Spellborn - Reborn"
theme = "hawksmouth"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "news"
    name = "News"
    url = "/news/"
    weight = 20

  [[menu.main]]
    identifier = "forum"
    name = "Forum"
    url = "https://forum.spellborn.org"
    weight = 30


  [[menu.main]]
  	identifier = "game1"
	  name = "High Houses"
	  url = "/content/high-houses/"
	  weight = 40

  [[menu.main]]
    identifier = "client1"
    name = "Get Started"
    url = "/content/getting-started/"
    weight = 50

  [[menu.main]]
    identifier = "Donate"
    name = "Donate"
    url = "https://donorbox.org/spellborn-reborn"
    weight = 40

  [[menu.main]]
    identifier = "status"
    name = "Server status"
    url = "/content/server-status/"
    weight = 60

  [[menu.footergame]]
    identifier = "highhouses"
    name = "High Houses"
    url = "/content/high-houses"
    weight = 10


  [[menu.footerquick]]
    identifier = "started"
    name = "Get Started"
    url = "/content/getting-started"
    weight = 10

  [[menu.footerquick]]
    identifier = "client"
    name = "Download installer/patcher"
    url = "https://files.spellborn.org/launcher/installer.exe"
    weight = 10


  [[menu.footermore]]
    identifier = "forum"
    name = "Forum"
    url = "https://forum.spellborn.org"
    weight = 10

  [[menu.footermore]]
    identifier = "discord"
    name = "Discord"
    url = "https://discord.gg/M8u7AsG"
    weight = 20


[params.meta]
description = "The Chronicles of Spellborn - Reborn. Enjoy the MMORPG, better than ever!"
keywords = "mmorpg, rpg, spellborn, chronicles of spellborn, enclave, game"

[params.hero]
herotitle = "EXPLORE THE DEMON ARMY CAMP"
herodiscription = "Never seen before content is now live!"
btnblue = "Learn more about Demon Army Camp"
btngreen = "Get started with Spellborn!"

[params.footer]
phone = "02920 000000"
email = "hello@example.com"
address = "123 Busy Street"

[markup.goldmark.renderer]
unsafe= true